# Generated by Django 5.0.3 on 2024-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Temporary', max_length=55),
            preserve_default=False,
        ),
    ]
