# Generated by Django 5.0.2 on 2024-02-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countDown', models.DateField(null=True)),
                ('team1Wins', models.IntegerField(default=0)),
                ('team2Wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('location', models.CharField(max_length=128)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.matchtable')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('matchDetail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('location', 'id')},
            },
        ),
        migrations.AddField(
            model_name='matchtable',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamName', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('publicProfile', models.ImageField(null=True, upload_to='')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='api.user')),
                ('users', models.ManyToManyField(related_name='team_player', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='matchtable',
            name='team1Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='matchtable',
            name='team2Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='api.team'),
        ),
        migrations.CreateModel(
            name='Divisons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publicProfile', models.ImageField(null=True, upload_to='')),
                ('position', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('teamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='matchtable',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courtschedule'),
        ),
    ]
