# Generated by Django 5.0.2 on 2024-02-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_division_teamindivision_delete_divisons'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courtschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matchtable',
            name='location',
        ),
        migrations.AddField(
            model_name='courtschedule',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='court_schedules', to='api.matchtable'),
        ),
        migrations.AlterField(
            model_name='courtschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
