# Generated by Django 5.0.2 on 2024-02-29 17:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_courtschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtable',
            name='status',
            field=models.CharField(choices=[('i', 'inProgress'), ('s', 'scheduled'), ('v', 'void'), ('f', 'finished')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
