# Generated by Django 5.0.3 on 2024-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_alter_division_publicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='status',
            field=models.CharField(choices=[('i', 'inProgress'), ('n', 'notStated'), ('v', 'void'), ('f', 'finished')], max_length=1, null=True),
        ),
    ]
